### ISSUE TITLE
Black thing in the background (Opera Dev 37.0.2142)

### ISSUE THREAD

**Issue by wandoschneider** [olsh/Feedly-Notifier-Opera#4]
Hi!

There's a black thing in the background of the extension's pop-up.
I have others similiar extensions, and they didin't show similar issue. Maybe it's an issue of the extension itself, rather than the browser. See the screenshot attached.
![capturar](https://cloud.githubusercontent.com/assets/8496997/13287831/bd59ed56-dae7-11e5-9764-bdb963de7485.PNG)

**Comment by olsh** [comment]
Hi,
Have you tried to reproduce it on a stable version of Opera?

**Comment by wandoschneider** [comment]
Hi,

It's only in Dev. I asked a Developer from Opera about that, and he said it's probably related to the extension. So I thought to give you a heads up before it hits Stable ;)

**Comment by olsh** [comment]
@wandoschneider sorry for the late response.
I can't reproduce it on Opera 38 dev and Opera 36 stable.

**Comment by wandoschneider** [comment]
Hi @olsh . Yeah, probably it was solved by the Opera team. Thanks anyway.
